### ISSUE TITLE
Magic numbers?

### ISSUE THREAD

**Issue by seb231** [MastodonC/witan.cic#9]
I was going to point out these magic numbers, but then realised they're not actually being used anywhere??

https://github.com/MastodonC/witan.cic/blob/343cb128cd7b2bae6c91c251efb35f46be696695/src/cic/projection.clj#L40

**Comment by henrygarner** [comment]
Fixed in https://github.com/MastodonC/witan.cic/commit/a37999f18a0f6685835d786d0ec7c21c1fc30ba2
